//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LWMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class repast_developmentEntities : DbContext
    {
        public repast_developmentEntities()
            : base("name=repast_developmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ar_internal_metadata> ar_internal_metadata { get; set; }
        public virtual DbSet<buy_gift_actives> buy_gift_actives { get; set; }
        public virtual DbSet<comments> comments { get; set; }
        public virtual DbSet<customers> customers { get; set; }
        public virtual DbSet<discount_actives> discount_actives { get; set; }
        public virtual DbSet<food_categories> food_categories { get; set; }
        public virtual DbSet<food_praises> food_praises { get; set; }
        public virtual DbSet<foods> foods { get; set; }
        public virtual DbSet<foods_food_categories> foods_food_categories { get; set; }
        public virtual DbSet<full_reduce_actives> full_reduce_actives { get; set; }
        public virtual DbSet<gift_foods> gift_foods { get; set; }
        public virtual DbSet<gourmet_palace_tables> gourmet_palace_tables { get; set; }
        public virtual DbSet<gourmet_palaces> gourmet_palaces { get; set; }
        public virtual DbSet<investments> investments { get; set; }
        public virtual DbSet<merchant_types> merchant_types { get; set; }
        public virtual DbSet<merchants> merchants { get; set; }
        public virtual DbSet<merchants_foods_comments> merchants_foods_comments { get; set; }
        public virtual DbSet<merchants_merchant_types> merchants_merchant_types { get; set; }
        public virtual DbSet<messages> messages { get; set; }
        public virtual DbSet<notice_forms> notice_forms { get; set; }
        public virtual DbSet<notices> notices { get; set; }
        public virtual DbSet<notices_roles> notices_roles { get; set; }
        public virtual DbSet<order_details> order_details { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<role_users> role_users { get; set; }
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<schema_migrations> schema_migrations { get; set; }
        public virtual DbSet<shops> shops { get; set; }
        public virtual DbSet<transaction_flow_logs> transaction_flow_logs { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<adverts> adverts { get; set; }
        public virtual DbSet<bank_cards> bank_cards { get; set; }
        public virtual DbSet<bonus_details> bonus_details { get; set; }
        public virtual DbSet<cost_types> cost_types { get; set; }
        public virtual DbSet<food_month_collects> food_month_collects { get; set; }
        public virtual DbSet<merchant_account_details> merchant_account_details { get; set; }
        public virtual DbSet<merchant_accounts> merchant_accounts { get; set; }
        public virtual DbSet<merchant_cost_types> merchant_cost_types { get; set; }
        public virtual DbSet<merchant_costs> merchant_costs { get; set; }
        public virtual DbSet<merchant_month_collects> merchant_month_collects { get; set; }
        public virtual DbSet<merchants_users> merchants_users { get; set; }
        public virtual DbSet<platform_cost_categories> platform_cost_categories { get; set; }
        public virtual DbSet<platform_costs> platform_costs { get; set; }
        public virtual DbSet<settings> settings { get; set; }
        public virtual DbSet<utilities> utilities { get; set; }
        public virtual DbSet<feedback> feedbacks { get; set; }
        public virtual DbSet<merchant_day_collects> merchant_day_collects { get; set; }
        public virtual DbSet<merchant_month_cost_details> merchant_month_cost_details { get; set; }
        public virtual DbSet<merchant_period_collects> merchant_period_collects { get; set; }
    }
}
