//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class merchants
    {
        public long id { get; set; }
        public Nullable<int> gourmet_palace_id { get; set; }
        public Nullable<int> shop_id { get; set; }
        public Nullable<int> boss { get; set; }
        public Nullable<int> shopowner { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> enter_at { get; set; }
        public Nullable<int> invest_status { get; set; }
        public string pic { get; set; }
        public string notice { get; set; }
        public string qrcode { get; set; }
        public Nullable<decimal> flavor { get; set; }
        public Nullable<decimal> service { get; set; }
        public Nullable<decimal> total_score { get; set; }
        public Nullable<bool> join_full_reduce { get; set; }
        public Nullable<bool> join_discount { get; set; }
        public Nullable<bool> join_buy_gift { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public Nullable<int> kitchen { get; set; }
        public Nullable<int> order_count { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public Nullable<System.DateTime> end_at { get; set; }
        public Nullable<int> status { get; set; }
    }
}
