//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_details
    {
        public long id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> food_id { get; set; }
        public Nullable<decimal> original_price { get; set; }
        public Nullable<decimal> discount_price { get; set; }
        public Nullable<int> num { get; set; }
        public string remark { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public Nullable<int> production_status { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
    }
}
