//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LWMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public long id { get; set; }
        public string login_name { get; set; }
        public string name { get; set; }
        public string photo { get; set; }
        public Nullable<int> created_user { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public string encrypted_password { get; set; }
        public Nullable<System.DateTime> remember_created_at { get; set; }
        public int sign_in_count { get; set; }
        public Nullable<System.DateTime> current_sign_in_at { get; set; }
        public Nullable<System.DateTime> last_sign_in_at { get; set; }
    }
}
